[package]
name = "rust-leetcode"
version = "0.1.0"
authors = ["Guangrui Wang <aguang.xyz@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10.7", features = ["json", "blocking"] }
serde = { version = "1.0.57", features = ["derive"] }
serde_json = "1.0.57"
